# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 300)
        Form.setMinimumSize(QtCore.QSize(420, 300))
        Form.setMaximumSize(QtCore.QSize(420, 300))
        Form.setStyleSheet("background-color:#EAEEEF;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #4F6C77;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #4F6C77;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.combo_category = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.combo_category.setFont(font)
        self.combo_category.setStyleSheet("color: #4F6C77;")
        self.combo_category.setObjectName("combo_category")
        self.combo_category.addItem("")
        self.gridLayout.addWidget(self.combo_category, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #4F6C77;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("color: #4F6C77;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.combo_term = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.combo_term.setFont(font)
        self.combo_term.setStyleSheet("color: #4F6C77;")
        self.combo_term.setObjectName("combo_term")
        self.combo_term.addItem("")
        self.gridLayout.addWidget(self.combo_term, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Статистика"))
        self.label_2.setText(_translate("Form", "Ваш прогресс по этому термину(категории):"))
        self.progressBar.setFormat(_translate("Form", "%p%"))
        self.pushButton.setText(_translate("Form", "НАЗАД"))
        self.label.setText(_translate("Form", "Выберите категорию"))
        self.combo_category.setItemText(0, _translate("Form", "Выберите категорию"))
        self.label_3.setText(_translate("Form", "Процент рассчитывается среди 20 последних ответов в тестах и карточках"))
        self.label_4.setText(_translate("Form", "Выберите термин:"))
        self.combo_term.setItemText(0, _translate("Form", "Выберите термин"))
