# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        Form.setMinimumSize(QtCore.QSize(600, 450))
        Form.setMaximumSize(QtCore.QSize(1280, 900))
        Form.setStyleSheet("background-color:#EAEEEF;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color:#4F6C77;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 1)
        self.add = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.add.setFont(font)
        self.add.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 2, 1, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("background-color: red;\n"
"color: white;")
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 9, 4, 1, 1)
        self.del_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.del_btn.setFont(font)
        self.del_btn.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#4F6C77;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.back = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color:#EAEEEF;\n"
"color:#4F6C77;")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(37)
        self.gridLayout.addWidget(self.tableWidget, 1, 3, 7, 2)
        self.load_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.load_btn.setFont(font)
        self.load_btn.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.load_btn.setObjectName("load_btn")
        self.gridLayout.addWidget(self.load_btn, 3, 1, 1, 1)
        self.del_catergory_button = QtWidgets.QPushButton(Form)
        self.del_catergory_button.setStyleSheet("background-color: #A7C4D4;\n"
"color: #F6E8DA;")
        self.del_catergory_button.setObjectName("del_catergory_button")
        self.gridLayout.addWidget(self.del_catergory_button, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование карточек"))
        self.pushButton.setText(_translate("Form", "Добавить категорию терминов"))
        self.comboBox.setItemText(0, _translate("Form", "Все термины"))
        self.add.setText(_translate("Form", "Добавить термин"))
        self.clear_btn.setText(_translate("Form", "ОЧИСТИТЬ!"))
        self.del_btn.setText(_translate("Form", "Удалить термин"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Ваши термины</p></body></html>"))
        self.back.setText(_translate("Form", "НАЗАД"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Термины"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Определения"))
        self.load_btn.setText(_translate("Form", "Загрузить таблицу"))
        self.del_catergory_button.setText(_translate("Form", "Удалить категорию"))
